export const STATE = {
  START_SCREEN: 'START_SCREEN',
  OPENING_CINEMATIC: 'OPENING_CINEMATIC',
  WORLD_MAP: 'WORLD_MAP',
  LEVEL_ARRIVAL: 'LEVEL_ARRIVAL',
  LEVEL_PLAY: 'LEVEL_PLAY',
  LEVEL_COMPLETE: 'LEVEL_COMPLETE',
  TRANSITION_TO_MAP: 'TRANSITION_TO_MAP',
};
